### ISSUE TITLE
Ask for some questions

### ISSUE THREAD

**Issue by zero863** [varunon9/webRTC#1]
Hello!  I'm studying WebRTC recently, Can  you tell me that where the 22 bit random string in your code to identify users is created，in which file？ I'm looking forward to hearing from you . thank you very much.

**Comment by varunon9** [comment]
That string is socket id. Check index.js line no 8. Whenever a new connection is made, that callback gets executed with socket object (new connection) as parameter. Socket internally generates id for each object which is unique. I am using this id to identify each users(connections). This id is sent to user so that he can share this with other users. Check index.js line no 13 and webrtc.js line no 49. Hope this answers your question.

**Comment by zero863** [comment]
Thank you very much for explaining it for me so detailedly , I want to use your code to further my understanding of WebRTC. but it seems a little troublesome to type 22 characters every time when I test it , I want to know whether I can shorten them, maybe 5; but I don't know where to modify it . Do you know where it is?

**Comment by varunon9** [comment]
Are you not able to copy and paste (and send using email/whatsapp)? You can
shorten it but that extra logic is not worrh if you only want to avoid
typing. Check index.js. everything is there.
